name: Build
on:
  push:
    branches:
      - main

jobs:
  test_types:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Test
        run: yarn && yarn test
